title: "Sport Fryslân • Interne wiki"
description: "Clubondersteuning — producten & diensten per thema"
baseurl: ""
url: ""
collections:
  producten: { output: true, permalink: /product/:name/ }
  themas:    { output: true, permalink: /thema/:name/ }
markdown: kramdown
kramdown: { input: GFM }
defaults:
  - { scope: { path: "", type: "producten" }, values: { layout: product, category: "Producten & diensten" } }
  - { scope: { path: "", type: "themas" },    values: { layout: theme, category: "Thema" } }
exclude: [README.md]
